#!/bin/bash
if [ $# != 3 ]
	then exit
fi
if [ $2 = "+" ]
then echo $(($1+$3))
elif [ $2 = "-" ]
then echo $(($1-$3))
elif [ $2 = "*" ]
then echo $(($1*$3))
elif [ $2 = "/" ]
then echo $(($1/$3))
else exit
fi
